
// Command to run script: npm run seedSeats
import 'dotenv/config';

import db from '../app/models/index.js';

await db.seat.bulkCreate(
    [
        {seatNumber: 1, rowNumber: 'A', seatStatus: 'working', isHandicap: true},
        {seatNumber: 2, rowNumber: 'A', seatStatus: 'working', isHandicap: true},
        {seatNumber: 3, rowNumber: 'A', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'A', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'A', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'A', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'A', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'A', seatStatus: 'working', isHandicap: true},
        {seatNumber: 9, rowNumber: 'A', seatStatus: 'working', isHandicap: true},
        {seatNumber: 1, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 2, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 3, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 9, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 10, rowNumber: 'B', seatStatus: 'working', isHandicap: false},
        {seatNumber: 1, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 2, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 3, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 9, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 10, rowNumber: 'C', seatStatus: 'working', isHandicap: false},
        {seatNumber: 1, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 2, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 3, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 9, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 10, rowNumber: 'D', seatStatus: 'working', isHandicap: false},
        {seatNumber: 1, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 2, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 3, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 9, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 10, rowNumber: 'E', seatStatus: 'working', isHandicap: false},
        {seatNumber: 1, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 2, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 3, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 9, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 10, rowNumber: 'F', seatStatus: 'working', isHandicap: false},
        {seatNumber: 1, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 2, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 3, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 9, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 10, rowNumber: 'G', seatStatus: 'working', isHandicap: false},
        {seatNumber: 1, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 2, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 3, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 4, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 5, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 6, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 7, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 8, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 9, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
        {seatNumber: 10, rowNumber: 'H', seatStatus: 'working', isHandicap: false},
    ],
    { fields: ['seatNumber', 'rowNumber', 'seatStatus', 'isHandicap'] },
);
