name: AWS DEPLOY TO STAGING

on:
  pull_request:
    types: [closed]
    branches:
      - dev
  workflow_dispatch:

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_PW: ${{ secrets.AWS_DB_PW}}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci

      - run: |
          {
            echo "DB_HOST='$DB_HOST'"
            echo "DB_PW='$DB_PW'"
            echo "DB_USER='$DB_USER'"
            echo "DB_NAME='$DB_NAME'"
            echo "SECRET_KEY='$SECRET_KEY'"
          } > .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/ticketing-system-backend"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@${{ secrets.REMOTE_HOST }}"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            sudo systemctl stop mysql
            cd nodeapps/ticketing-system-backend
            sudo cp ticketing-system-backend.service /lib/systemd/system/ticketing-system-backend.service
            sudo systemctl daemon-reload
            sudo systemctl enable ticketing-system-backend
            sudo systemctl restart ticketing-system-backend
